[phases.setup]
aptPkgs = [
    "libgl1",
    "libglib2.0-0"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "pip uninstall -y opencv-python opencv-contrib-python",
    "pip install opencv-python-headless"
]